In [1]:
# EJEMPLO
import numpy as np
import pandas as pd
from pysfa import SFA
from pysfa.dataset import load_Tim_Coelli_frontier


# import the data from Tim Coelli Frontier 4.1
df = load_Tim_Coelli_frontier(x_select=['labour', 'capital'],
                              y_select=['output'])
y = np.log(df.y)
x = np.log(df.x)

# Estimate SFA model
res = SFA.SFA(y, x, fun=SFA.FUN_PROD, method=SFA.TE_teJ)
res.optimize()
# print estimates
print(res.get_beta())
print(res.get_residuals())

# print estimated parameters
print(res.get_lambda())
print(res.get_sigma2())
print(res.get_sigmau2())
print(res.get_sigmav2())

# print statistics
print(res.get_pvalue())
print(res.get_tvalue())
print(res.get_std_err())

# OR print summary
print(res.summary())

# print TE
print(res.get_technical_efficiency())

[0.56161704 0.53648021 0.28110254]
[-0.55366325 -0.1357829  -0.39459059 -0.34712217 -0.469195   -0.27964047
 -0.73686372 -0.36989759 -0.0862761  -0.32423006 -0.78151592  0.50969401
 -1.02894071 -0.62139557  0.03213954 -0.7724152  -0.42428165 -0.32137011
 -0.03721398 -0.20167189 -0.39858184  0.02490608 -0.11026611 -0.33709419
 -0.81867336  0.15473957 -0.1915553  -0.26664422 -0.04170548 -0.61576202
 -0.70525042 -0.3437392   0.07048206 -1.10772322 -1.33436079  0.10759289
 -0.09558622 -0.49555814 -0.50756103 -0.10454302 -0.32003382 -0.48888741
 -0.20755554  0.09397636 -0.35806363 -0.39529333 -0.05190512 -0.25809709
 -0.50930356 -0.85591875 -0.09149316 -0.06091847 -0.0279558  -0.33060793
 -0.17328183 -0.31941201  0.03061722 -0.52456398 -0.03940645 -0.43320822]
1.9827044428722016
0.21699993937725964
0.17299369425363184
0.04400624512362781
[0.003 0.003 0.099 0.001]
[3.05018539 3.07264968 1.67830047 3.65961984]
[0.18412554 0.17459856 0.16749238 0.5417788 ]
             Parameters   Std.err  t-

In [2]:
import numpy as np
import pandas as pd
from pysfa import SFA
from pysfa.dataset import load_Tim_Coelli_frontier


# import the data from Tim Coelli Frontier 4.1
df = load_Tim_Coelli_frontier(x_select=['labour', 'capital'],
                              y_select=['output'])

print(df)
# y = np.log(df.y)
# x = np.log(df.x)

# # Estimate SFA model
# res = SFA.SFA(y, x, fun=SFA.FUN_PROD, method=SFA.TE_teJ)
# res.optimize()
# # print estimates
# print(res.get_beta())
# print(res.get_residuals())

# # print estimated parameters
# print(res.get_lambda())
# print(res.get_sigma2())
# print(res.get_sigmau2())
# print(res.get_sigmav2())

# # print statistics
# print(res.get_pvalue())
# print(res.get_tvalue())
# print(res.get_std_err())

# # OR print summary
# print(res.summary())

# # print TE
# print(res.get_technical_efficiency())

In [21]:
import pysfa
import pandas as pd
import numpy as np

# cargar datos consolidados
df = pd.read_csv('df_consolidado_final_v2.csv', sep=',')

# pasar valores con -- a 0 en todas las columnas
df = df.replace({'--': 0})

# para las columnas Consulta, GRDxEgreso, Bienes y servicios, Remuneraciones, Dias Cama Disponibles, Consultas Urgencias, Examenes y Quirofanos transformar missing en 0
df['Consultas'] = df['Consultas'].fillna(0)
df['GRDxEgreso'] = df['GRDxEgreso'].fillna(0)
df['Bienes y servicios'] = df['Bienes y servicios'].fillna(0)
df['Remuneraciones'] = df['Remuneraciones'].fillna(0)
df['Dias Cama Disponibles'] = df['Dias Cama Disponibles'].fillna(0)
df['Consultas Urgencias'] = df['Consultas Urgencias'].fillna(0)
df['Examenes'] = df['Examenes'].fillna(0)
df['Quirofanos'] = df['Quirofanos'].fillna(0)

# drop filas con 0 en alguna columna
df = df.dropna()

In [22]:
# pasar columna Consultas a float
df['Consultas'] = df['Consultas'].astype(int)
df['GRDxEgreso'] = df['GRDxEgreso'].astype(int)
df['Bienes y servicios'] = df['Bienes y servicios'].astype(int)
df['Remuneraciones'] = df['Remuneraciones'].astype(int)
df['Dias Cama Disponibles'] = df['Dias Cama Disponibles'].astype(int)
df['Consultas Urgencias'] = df['Consultas Urgencias'].astype(int)
df['Examenes'] = df['Examenes'].astype(int)
df['Quirofanos'] = df['Quirofanos'].astype(int)

In [23]:
# filtrar datos solo con año 2014
df = df[df['Año'] == 2014]

# obtener una muestra de 10 hospitales
df = df.sample(n=10, random_state=1)

In [24]:
df

hospital_id  region_id  \
16        105105          4   
145       112103         13   
95        128109          8   
158       113150         13   
47        115106          6   
118       122101         14   
53        115112          6   
31        107105          5   
4         103102          2   
35        107109          5   

                                         hospital_name  \
16              Hospital San Juan de Dios (Combarbalá)   
145  Instituto Nacional de Enfermedades Respiratori...   
95   Hospital Provincial Dr. Rafael Avaría (Curanil...   
158                           Hospital San Luis (Buin)   
47                              Hospital de Pichidegua   
118                                 Hospital de Corral   
53                               Hospital de Pichilemu   
31                     Hospital San Agustín (La Ligua)   
4              Hospital Dr. Marcos Macuada (Tocopilla)   
35   Hospital Juana Ross de Edwards (Peñablanca - V...   

     hospital_alternative_name  latitud  longitud  Consultas  GRDxEgreso  \
16         Hospital Combarbalá -31.2125  -71.2355        307         181   
145         Hospital del Tórax -33.4428  -70.6193      38204        6149   
95        Hospital Curanilahue -37.4764  -73.3437      27426        3739   
158  Hospital San Luis de Buin -33.7336  -70.7478      24955        2849   
47         Hospital Pichidegua -34.2998  -71.2786         15         239   
118         Hospital de Corral -39.8826  -73.4306          4         186   
53          Hospital Pichilemu -34.3869  -72.0095         83         371   
31        Hospital de La Ligua -32.4478  -71.2316       6119         607   
4        Hospital de Tocopilla -22.0882  -70.1929       4752         746   
35         Hospital Peñablanca -33.0424  -71.3724       1201        1216   

     Bienes y servicios  Remuneraciones  Dias Cama Disponibles  \
16              1251524          304085                   7347   
145             8552125        12167125                  46880   
95              9087051         3257555                  37377   
158             6293464         2001783                  35636   
47               729578          241854                   4566   
118             1082169          283485                   2582   
53              1097711          431671                   8808   
31              2529715          973515                  21535   
4               3524477         1380911                  14564   
35              2856757         1439798                  29220   

     Consultas Urgencias  Examenes  Quirofanos   Año  
16                 10696     47647           0  2014  
145                    0    416083           0  2014  
95                 46524    409246         178  2014  
158               100459    183060         191  2014  
47                 26757     49708           0  2014  
118                11456     25882           0  2014  
53                 24358    135034           0  2014  
31                 46338    107964           0  2014  
4                  32963    148503           0  2014  
35                 44651    150252           0  2014

In [25]:
import numpy as np
# 2. Definir log-variables

# Asegura que las columnas sean numéricas
df['Remuneraciones'] = pd.to_numeric(df['Remuneraciones'], errors='coerce')
df['Bienes y servicios'] = pd.to_numeric(df['Bienes y servicios'], errors='coerce')
df['Dias Cama Disponibles'] = pd.to_numeric(df['Dias Cama Disponibles'], errors='coerce')
df['Consultas'] = pd.to_numeric(df['Consultas'], errors='coerce')

x = np.log(df[['Remuneraciones', 'Bienes y servicios', 'Dias Cama Disponibles']]).to_numpy()
y = np.log(df['Consultas']).to_numpy()

In [26]:
x

array([[12.62506255, 14.03987257,  8.90204735],
       [16.3142482 , 15.96169035, 10.75534642],
       [14.99648747, 16.02236099, 10.52881082],
       [14.50954884, 15.65502219, 10.48111164],
       [12.39608952, 13.50022156,  8.42639283],
       [12.55491449, 13.89447792,  7.85631957],
       [12.975419  , 13.90873766,  9.08341568],
       [13.78866851, 14.74361721,  9.9774348 ],
       [14.13825398, 15.07524261,  9.58630801],
       [14.18001338, 14.86519762, 10.28260869]])

In [27]:
cols = ["Remuneraciones", "Bienes y servicios", "Dias Cama Disponibles", "Consultas"]

# identifica filas con ±inf o números no finitos
mask_bad = ~np.isfinite(df[cols].to_numpy())
rows_bad = np.where(mask_bad.any(axis=1))[0]

print("Filas problemáticas:", rows_bad)        # índices con inf
print(df.iloc[rows_bad][cols])


Filas problemáticas: []
Empty DataFrame
Columns: [Remuneraciones, Bienes y servicios, Dias Cama Disponibles, Consultas]
Index: []


In [28]:
df[cols] = df[cols].replace(0, np.nan)          # evita -inf
df = df.replace([np.inf, -np.inf], np.nan)      # purga infinitos

# Imputación rápida o eliminación:
df = df.dropna(subset=cols)                     # opción 1: descartar
# o bien:
# df[cols] = df[cols].fillna(df[cols].median())   # opción 2: imputar

In [29]:
from pysfa import SFA

# 3. Crear y optimizar SFA
sfa = SFA.SFA(y, x, fun=SFA.FUN_PROD, method=SFA.TE_teJ)
sfa.optimize()
# 4. Añadir eficiencia al DataFrame
df['Eff_SFA'] = sfa.get_technical_efficiency()
# 5. Guardar para el dashboard
df[['hospital_name', 'Eff_SFA']].to_csv("sfa_scores.csv", index=False)

# print estimates
print("Coeficientes de función de producción:", sfa.get_beta())
print("Residuales (diferencia entre observado y esperado):", sfa.get_residuals())

print("\n")

# print estimated parameters
print("Lambda (varianza ineficiencia / varianza ruido):", sfa.get_lambda())
print("Sigma2 (varianza total del error):", sfa.get_sigma2())
print("Sigma_u2 (varianza de la ineficiencia):", sfa.get_sigmau2())
print("Sigma_v2 (varianza del ruido estadístico):", sfa.get_sigmav2())

print("\n")

# print statistics
print("P-value de los coeficientes:", sfa.get_pvalue())
print("T-value de los coeficientes:", sfa.get_tvalue())
print("Error estándar de los coeficientes:", sfa.get_std_err())

print("\n")

# OR print summary
print("Resumen del modelo SFA:\n", sfa.summary())

print("\n")

# print TE
print("Eficiencia técnica individuo a individuo (TE):", sfa.get_technical_efficiency())

Coeficientes de función de producción: [-34.48459563  -0.72074451   2.03111475   2.26869661]
Residuales (diferencia entre observado y esperado): [ 0.59825103 -0.02694669 -0.91745273 -0.50850612 -0.41036867 -1.12510891
 -0.6023583   0.56010588  0.77301334 -1.72536934]


Lambda (varianza ineficiencia / varianza ruido): 0.5799663471961503
Sigma2 (varianza total del error): 0.7144204020041808
Sigma_u2 (varianza de la ineficiencia): 0.17981903207946887
Sigma_v2 (varianza del ruido estadístico): 0.5346013699247119


P-value de los coeficientes: [0.056 0.372 0.279 0.012 0.871]
T-value de los coeficientes: [-2.36102162 -0.96557428  1.19073233  3.52519387  0.16906902]
Error estándar de los coeficientes: [14.60579407  0.74644129  1.70576938  0.64356648  3.43035249]


             Parameters    Std.err  t-value  Pr(>|t|)
(Intercept)   -34.48460  14.605794   -2.361     0.056
x1             -0.72074   0.746441   -0.966     0.372
x2              2.03111   1.705769    1.191     0.279
x3              