In [ ]:
import numpy as np
import pandas as pd
from pysfa import SFA
from pysfa.dataset import load_Tim_Coelli_frontier


# import the data from Tim Coelli Frontier 4.1
df = load_Tim_Coelli_frontier(x_select=['labour', 'capital'],
                              y_select=['output'])

print(df)
# y = np.log(df.y)
# x = np.log(df.x)

# # Estimate SFA model
# res = SFA.SFA(y, x, fun=SFA.FUN_PROD, method=SFA.TE_teJ)
# res.optimize()
# # print estimates
# print(res.get_beta())
# print(res.get_residuals())

# # print estimated parameters
# print(res.get_lambda())
# print(res.get_sigma2())
# print(res.get_sigmau2())
# print(res.get_sigmav2())

# # print statistics
# print(res.get_pvalue())
# print(res.get_tvalue())
# print(res.get_std_err())

# # OR print summary
# print(res.summary())

# # print TE
# print(res.get_technical_efficiency())

[[12.778]
 [24.285]
 [20.855]
 [13.213]
 [12.018]
 [15.284]
 [ 6.707]
 [21.656]
 [14.574]
 [13.743]
 [ 3.793]
 [37.118]
 [11.235]
 [ 9.237]
 [12.634]
 [ 9.677]
 [18.315]
 [17.094]
 [21.566]
 [18.872]
 [17.102]
 [14.55 ]
 [24.031]
 [ 6.787]
 [ 6.388]
 [32.996]
 [26.04 ]
 [16.619]
 [10.065]
 [ 6.554]
 [ 3.539]
 [ 1.66 ]
 [16.775]
 [10.085]
 [ 7.064]
 [31.793]
 [32.303]
 [14.571]
 [12.258]
 [12.683]
 [12.88 ]
 [15.841]
 [24.623]
 [20.571]
 [21.208]
 [12.493]
 [32.313]
 [15.575]
 [13.414]
 [10.228]
 [19.927]
 [26.938]
 [35.825]
 [12.768]
 [18.412]
 [19.853]
 [ 3.269]
 [21.358]
 [27.124]
 [14.105]]


In [ ]:
import pysfa
import pandas as pd
import numpy as np

# cargar datos consolidados
df = pd.read_csv('df_consolidado_final_v2.csv', sep=',')

# pasar valores con -- a 0 en todas las columnas
df = df.replace({'--': 0})

# para las columnas Consulta, GRDxEgreso, Bienes y servicios, Remuneraciones, Dias Cama Disponibles, Consultas Urgencias, Examenes y Quirofanos transformar missing en 0
df['Consultas'] = df['Consultas'].fillna(0)
df['GRDxEgreso'] = df['GRDxEgreso'].fillna(0)
df['Bienes y servicios'] = df['Bienes y servicios'].fillna(0)
df['Remuneraciones'] = df['Remuneraciones'].fillna(0)
df['Dias Cama Disponibles'] = df['Dias Cama Disponibles'].fillna(0)
df['Consultas Urgencias'] = df['Consultas Urgencias'].fillna(0)
df['Examenes'] = df['Examenes'].fillna(0)
df['Quirofanos'] = df['Quirofanos'].fillna(0)

# drop filas con 0 en alguna columna
df = df.dropna()

In [ ]:
# pasar columna Consultas a float
df['Consultas'] = df['Consultas'].astype(int)
df['GRDxEgreso'] = df['GRDxEgreso'].astype(int)
df['Bienes y servicios'] = df['Bienes y servicios'].astype(int)
df['Remuneraciones'] = df['Remuneraciones'].astype(int)
df['Dias Cama Disponibles'] = df['Dias Cama Disponibles'].astype(int)
df['Consultas Urgencias'] = df['Consultas Urgencias'].astype(int)
df['Examenes'] = df['Examenes'].astype(int)
df['Quirofanos'] = df['Quirofanos'].astype(int)

In [ ]:
# filtrar datos solo con año 2014
df = df[df['Año'] == 2014]

# obtener una muestra de 10 hospitales
df = df.sample(n=10, random_state=1)

In [42]:
df

hospital_id  region_id  \
16        105105          4   
145       112103         13   
95        128109          8   
158       113150         13   
47        115106          6   
118       122101         14   
53        115112          6   
31        107105          5   
4         103102          2   
35        107109          5   

                                         hospital_name  \
16              Hospital San Juan de Dios (Combarbalá)   
145  Instituto Nacional de Enfermedades Respiratori...   
95   Hospital Provincial Dr. Rafael Avaría (Curanil...   
158                           Hospital San Luis (Buin)   
47                              Hospital de Pichidegua   
118                                 Hospital de Corral   
53                               Hospital de Pichilemu   
31                     Hospital San Agustín (La Ligua)   
4              Hospital Dr. Marcos Macuada (Tocopilla)   
35   Hospital Juana Ross de Edwards (Peñablanca - V...   

     hospital_alternative_name  latitud  longitud  Consultas  GRDxEgreso  \
16         Hospital Combarbalá -31.2125  -71.2355      307.0   181.26822   
145         Hospital del Tórax -33.4428  -70.6193    38204.0  6149.69340   
95        Hospital Curanilahue -37.4764  -73.3437    27426.0  3739.04160   
158  Hospital San Luis de Buin -33.7336  -70.7478    24955.0  2849.75570   
47         Hospital Pichidegua -34.2998  -71.2786       15.0   239.24914   
118         Hospital de Corral -39.8826  -73.4306        4.0   186.22994   
53          Hospital Pichilemu -34.3869  -72.0095       83.0   371.79714   
31        Hospital de La Ligua -32.4478  -71.2316     6119.0   607.53564   
4        Hospital de Tocopilla -22.0882  -70.1929     4752.0   746.24524   
35         Hospital Peñablanca -33.0424  -71.3724     1201.0  1216.79064   

    Bienes y servicios Remuneraciones  Dias Cama Disponibles  \
16             1251524         304085                 7347.0   
145            8552125       12167125                46880.0   
95             9087051        3257555                37377.0   
158            6293464        2001783                35636.0   
47              729578         241854                 4566.0   
118            1082169         283485                 2582.0   
53             1097711         431671                 8808.0   
31             2529715         973515                21535.0   
4              3524477        1380911                14564.0   
35             2856757        1439798                29220.0   

     Consultas Urgencias  Examenes  Quirofanos   Año  
16               10696.0   47647.0         0.0  2014  
145                  0.0  416083.0         0.0  2014  
95               46524.0  409246.0       178.0  2014  
158             100459.0  183060.0       191.0  2014  
47               26757.0   49708.0         0.0  2014  
118              11456.0   25882.0         0.0  2014  
53               24358.0  135034.0         0.0  2014  
31               46338.0  107964.0         0.0  2014  
4                32963.0  148503.0         0.0  2014  
35               44651.0  150252.0         0.0  2014

In [ ]:
import numpy as np
# 2. Definir log-variables

# Asegura que las columnas sean numéricas
df['Remuneraciones'] = pd.to_numeric(df['Remuneraciones'], errors='coerce')
df['Bienes y servicios'] = pd.to_numeric(df['Bienes y servicios'], errors='coerce')
df['Dias Cama Disponibles'] = pd.to_numeric(df['Dias Cama Disponibles'], errors='coerce')
df['Consultas'] = pd.to_numeric(df['Consultas'], errors='coerce')

x = np.log(df[['Remuneraciones', 'Bienes y servicios', 'Dias Cama Disponibles']]).to_numpy()
y = np.log(df['Consultas']).to_numpy()

In [50]:
x

array([[12.62506255, 14.03987257,  8.90204735],
       [16.3142482 , 15.96169035, 10.75534642],
       [14.99648747, 16.02236099, 10.52881082],
       [14.50954884, 15.65502219, 10.48111164],
       [12.39608952, 13.50022156,  8.42639283],
       [12.55491449, 13.89447792,  7.85631957],
       [12.975419  , 13.90873766,  9.08341568],
       [13.78866851, 14.74361721,  9.9774348 ],
       [14.13825398, 15.07524261,  9.58630801],
       [14.18001338, 14.86519762, 10.28260869]])

In [51]:
cols = ["Remuneraciones", "Bienes y servicios", "Dias Cama Disponibles", "Consultas"]

# identifica filas con ±inf o números no finitos
mask_bad = ~np.isfinite(df[cols].to_numpy())
rows_bad = np.where(mask_bad.any(axis=1))[0]

print("Filas problemáticas:", rows_bad)        # índices con inf
print(df.iloc[rows_bad][cols])


Filas problemáticas: []
Empty DataFrame
Columns: [Remuneraciones, Bienes y servicios, Dias Cama Disponibles, Consultas]
Index: []


In [52]:
df[cols] = df[cols].replace(0, np.nan)          # evita -inf
df = df.replace([np.inf, -np.inf], np.nan)      # purga infinitos

# Imputación rápida o eliminación:
df = df.dropna(subset=cols)                     # opción 1: descartar
# o bien:
# df[cols] = df[cols].fillna(df[cols].median())   # opción 2: imputar

In [54]:
from pysfa import SFA

# 3. Crear y optimizar SFA
sfa = SFA.SFA(y, x, fun=SFA.FUN_PROD, method=SFA.TE_teJ)
sfa.optimize()
# 4. Añadir eficiencia al DataFrame
df['Eff_SFA'] = sfa.get_technical_efficiency()
# 5. Guardar para el dashboard
df[['hospital_name', 'Eff_SFA']].to_csv("sfa_scores.csv", index=False)

# print estimates
print(sfa.get_beta())
print(sfa.get_residuals())

# print estimated parameters
print(sfa.get_lambda())
print(sfa.get_sigma2())
print(sfa.get_sigmau2())
print(sfa.get_sigmav2())

# print statistics
print(sfa.get_pvalue())
print(sfa.get_tvalue())
print(sfa.get_std_err())

# OR print summary
print(sfa.summary())

# print TE
print(sfa.get_technical_efficiency())

[-34.48458512  -0.72074494   2.03111407   2.26869776]
[ 0.59824512 -0.02695186 -0.91745817 -0.50851196 -0.41037449 -1.12511375
 -0.60236436  0.5600997   0.77300799 -1.72537562]
0.5799770906008119
0.7144242575530582
0.1798249877264723
0.5345992698265859
[0.002 0.324 0.067 0.019 0.928]
[-5.29717318 -1.07417073  2.23444244  3.17306643  0.09422648]
[6.50999768 0.67097801 0.90900264 0.7149859  6.1551388 ]
             Parameters   Std.err  t-value  Pr(>|t|)
(Intercept)   -34.48459  6.509998   -5.297     0.002
x1             -0.72074  0.670978   -1.074     0.324
x2              2.03111  0.909003    2.234     0.067
x3              2.26870  0.714986    3.173     0.019
lambda          0.57998  6.155139    0.094     0.928
sigma2:  0.71442
sigmav2:  0.5346 ; sigmau2:  0.17982
log likelihood:  11.63279
None
[0.78331326 0.74440924 0.67426394 0.70867424 0.7163787  0.65542214
 0.70110391 0.78116737 0.79279041 0.59652397]
